"""add events rules alerts

Revision ID: a1093f11e6de
Revises: 41bf48cce743
Create Date: 2026-08-27 12:11:53.024236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1093f11e6de'
down_revision: Union[str, Sequence[str], None] = '41bf48cce743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('severity', sa.SmallInteger(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('severity BETWEEN 1 AND 5', name='ck_events_severity_range'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_events_source_external')
    )
    op.create_index('ix_events_source_occurred_at', 'events', ['source_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('ix_events_type_severity', 'events', ['event_type', 'severity'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('min_severity', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('window_sec', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_severity BETWEEN 1 AND 5', name='ck_rules_min_severity_range'),
    sa.CheckConstraint('threshold > 0', name='ck_rules_threshold_positive'),
    sa.CheckConstraint('window_sec > 0', name='ck_rules_window_sec_positive'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'resolved')", name='ck_alerts_status'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'source_id', 'window_start', name='uq_alerts_rule_source_window')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('rules')
    op.drop_index('ix_events_type_severity', table_name='events')
    op.drop_index('ix_events_source_occurred_at', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
